image: openjdk:8

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules
        - .maven
stages:
    - build
    - test
    - package
    - deploy

before_script:
    - export MAVEN_USER_HOME=`pwd`/.maven
    - chmod +x mvnw
    - ./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-yarn -DnodeVersion=v8.9.4 -DyarnVersion=v1.3.2
    - ./mvnw com.github.eirslett:frontend-maven-plugin:yarn

maven-build:
    stage: build
    script: ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME

maven-test:
    stage: test
    script:
        - ./mvnw test -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/surefire-reports/*
maven-front-test:
    stage: test
    script:
        - ./mvnw com.github.eirslett:frontend-maven-plugin:yarn -Dfrontend.yarn.arguments=test
    artifacts:
        paths:
            - target/test-results/karma/*
gatling-test:
    stage: test
    allow_failure: true
    script:
        - ./mvnw gatling:execute -Dmaven.repo.local=$MAVEN_USER_HOME
    before_script:
        - export MAVEN_USER_HOME=`pwd`/.maven
        - chmod +x mvnw
        - ./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-yarn -DnodeVersion=v8.9.4 -DyarnVersion=v1.3.2
        - ./mvnw com.github.eirslett:frontend-maven-plugin:yarn
        - ./mvnw &
    artifacts:
        paths:
            - target/gatling/*
maven-deploy:
    stage: deploy
    script:
        - ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy-war -DskipTests -Pprod -Dheroku.appName=elmoreplus
    artifacts:
        paths:
            - target/*.war
