version: '2'
services:
    elmoreplus-app:
        image: elmoreplus
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://elmoreplus-postgresql:5432/elmoreplus
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    elmoreplus-postgresql:
        extends:
            file: postgresql.yml
            service: elmoreplus-postgresql
